fn main() {
    // The `opencl` feature takes precedence over the CUDA `gpu` backend so a
    // build that explicitly opts into OpenCL never also drags in nvcc.
    #[cfg(feature = "opencl")]
    build_opencl_libs();
    #[cfg(all(feature = "gpu", not(feature = "opencl")))]
    build_cuda_libs();
}

#[cfg(all(feature = "gpu", not(feature = "opencl")))]
fn build_cuda_libs() {
    println!("cargo::rerun-if-changed=kernels/");
    println!("cargo::rerun-if-env-changed=VANITY_CUDA_ARCH");

    let mut build = cc::Build::new();
    build
        .cuda(true)
        .include("kernels")
        .file("kernels/utils.cu")
        .file("kernels/vanity.cu")
        .file("kernels/vanity_keypair.cu")
        .file("kernels/base58.cu")
        .file("kernels/sha256.cu")
        .flag("-cudart=static");

    // Cargo's release profile keeps Rust debug symbols, but forwarding that
    // setting to nvcc enables `-G` device-debug code and can reduce kernel
    // throughput by orders of magnitude. Keep `-G` available in debug builds.
    if std::env::var("PROFILE").as_deref() == Ok("release") {
        build.debug(false);
    }

    // Which GPU architectures to generate code for. A cubin built for one
    // compute capability only runs on that capability (e.g. an sm_89 cubin
    // will NOT load on an sm_86 RTX 3090), and PTX only JITs *upward*, so a
    // single high target silently fails to launch on older cards. Default to
    // native SASS for the common Turing..Ada cards plus a PTX fallback for
    // anything newer; override with VANITY_CUDA_ARCH for a faster, targeted
    // build, e.g. `VANITY_CUDA_ARCH=86` (RTX 3090) or `VANITY_CUDA_ARCH=80,89`.
    match std::env::var("VANITY_CUDA_ARCH") {
        Ok(spec) if !spec.trim().is_empty() => {
            for arch in spec.split([';', ',']).map(str::trim).filter(|s| !s.is_empty()) {
                build.flag(&format!("-gencode=arch=compute_{arch},code=sm_{arch}"));
            }
        }
        _ => {
            for arch in ["75", "80", "86", "89"] {
                build.flag(&format!("-gencode=arch=compute_{arch},code=sm_{arch}"));
            }
            // PTX fallback so newer GPUs (e.g. sm_90 H100) still JIT-load.
            build.flag("-gencode=arch=compute_89,code=compute_89");
        }
    }

    build.compile("libvanity.a");

    // Add link directory
    println!("cargo:rustc-link-search=native=/usr/local/cuda/lib64");
    println!("cargo:rustc-link-lib=cudart");
    println!("cargo:rustc-link-lib=cuda");

    // Emit the location of the compiled library
    let out_dir = std::env::var("OUT_DIR").unwrap();
    println!("cargo:rustc-link-search=native={}", out_dir);
}

/// Build the OpenCL backend: embed the .cl kernel sources into a C header so
/// they can be compiled at runtime, then compile the C host (kernels/opencl/
/// host.c) which exposes the same extern "C" ABI as the CUDA host.
#[cfg(feature = "opencl")]
fn build_opencl_libs() {
    use std::path::Path;

    println!("cargo::rerun-if-changed=kernels/opencl/");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();

    // Each .cl file becomes `static const char *CL_<NAME> = "...";`. The host
    // assembles these into per-program source arrays for clCreateProgramWithSource.
    let cl_files = [
        ("CL_PREAMBLE", "preamble.cl"),
        ("CL_SHA256", "sha256.cl"),
        ("CL_SHA512", "sha512.cl"),
        ("CL_BASE58", "base58.cl"),
        ("CL_FE", "fe.cl"),
        ("CL_PRECOMP", "precomp.cl"),
        ("CL_GE", "ge.cl"),
        ("CL_VANITY", "vanity.cl"),
        ("CL_KEYPAIR", "keypair.cl"),
        ("CL_DOPPLER", "doppler.cl"),
    ];

    let mut header = String::from("/* Generated by build.rs — do not edit. */\n#pragma once\n\n");
    for (sym, file) in cl_files {
        let path = format!("kernels/opencl/{file}");
        let src = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("reading {path}: {e}"));
        header.push_str(&format!("static const char *{sym} =\n"));
        for raw in src.split('\n') {
            let line = raw.strip_suffix('\r').unwrap_or(raw);
            let esc = line.replace('\\', "\\\\").replace('"', "\\\"");
            header.push_str(&format!("    \"{esc}\\n\"\n"));
        }
        header.push_str("    ;\n\n");
    }

    let header_path = Path::new(&out_dir).join("cl_sources.h");
    std::fs::write(&header_path, header).expect("writing cl_sources.h");

    let mut build = cc::Build::new();
    build
        .file("kernels/opencl/host.c")
        .include(&out_dir);
    if target_os == "macos" {
        build.flag("-Wno-deprecated-declarations");
        // Pin the SDK so the OpenCL.framework headers resolve regardless of
        // which clang (e.g. a Homebrew one) cc-rs picks up.
        if let Ok(out) = std::process::Command::new("xcrun")
            .args(["--show-sdk-path"])
            .output()
        {
            if out.status.success() {
                let sdk = String::from_utf8_lossy(&out.stdout).trim().to_string();
                if !sdk.is_empty() {
                    build.flag("-isysroot").flag(&sdk);
                }
            }
        }
    }
    build.compile("vanity");

    // Link the OpenCL ICD loader / framework.
    if target_os == "macos" {
        println!("cargo:rustc-link-lib=framework=OpenCL");
    } else {
        println!("cargo:rustc-link-lib=OpenCL");
    }

    println!("cargo:rustc-link-search=native={}", out_dir);
}
